### PR TITLE
Avoid forcing all users to install TeX fonts for all supported languages

### PR DESCRIPTION
**Pull request by ojwb**
Thanks to Cawa Sorix for working this out.

This patch has been in the Debian package since 5.3.11-1 in 2013.

### CODE REVIEW

**Comment by mbudaj** [comment]
I'm not sure about this one. This patch actually fixes the effects of another Debian patch (https://sources.debian.net/patches/therion/5.3.16-10/80remove-czech-fonts-default.patch/).
I guess that the referenced patch was intended to remove the dependence on czech/slovak & cyrillic fonts; however this PR introduces the dependency on czech fonts again (as they are required e.g. for samples generation). I think the best way how to deal with this is to use no of the two Debian patches and have therion support czech/slovak and cyrillic out of the box. Adding a dependecy on two tex language packages should not bloat the system in a substantial way.

**Comment by ojwb** [comment]
Oddly enough I asked Wookey about that other patch last night, and wondered if the two were related.

The font packages are large enough that I can see why @wookey wanted to make them optional - on x86-64 Debian unstable the installed sizes (which don't include dependencies) are:

* 39,354.0 kB [texlive-lang-cyrillic](https://packages.debian.org/sid/texlive-lang-cyrillic)
* 14,363.0 kB [texlive-lang-czechslovak](https://packages.debian.org/sid/texlive-lang-czechslovak)

For comparison:

* 4,473.0 kB [therion (without loch)](https://packages.debian.org/sid/therion)
* 2,549.0 kB [loch](https://packages.debian.org/sid/therion-viewer)
* 1,792.0 kB [survex (without aven)](https://packages.debian.org/sid/survex)
* 2,979.0 kB [aven](https://packages.debian.org/sid/survex-aven)
* 3,166.0 kB [wxbase3.0-0v5](https://packages.debian.org/sid/libwxbase3.0-0v5)
* 17,683.0 kB [wxgtk3.0-0v5](https://packages.debian.org/sid/libwxgtk3.0-0v5)

Of course there are other dependencies, but people are likely to have at least some of them installed for other reasons (and wxwidgets may well be).  It looks like making these fonts a hard dependency could easily double the amount of extra stuff you'd typically need to install to install a working therion setup.

And as more languages are supported, the bloat gets worse - e.g. I noticed Chinese support got added recently, which presumably means we'll soon also need everyone to install:

* 79,867.0 kB [texlive-lang-chinese](https://packages.debian.org/sid/texlive-lang-chinese)

So a solution which allows them to be installed optionally seems desirable.

**Comment by mbudaj** [comment]
This PR requires texlive-lang-czechslovak anyway.

Regarding Chinese, the best way to use it in therion is to define pdf-fonts in the INI file. It is much more flexible (although much slower) way than using traditional TeX fonts.

I'll discuss this with @smudrak.

**Comment by ojwb** [comment]
> This PR requires texlive-lang-czechslovak anyway.

Sure, I understand there are issues with the patch in this PR (and the related Debian patch which actually makes this one necessary).  However the motivating issue remains - it's undesirable to have to install all the packages for all the TeX fonts which therion could possibly use.

Retitling to reflect that.  I would remove the patch and convert it to an issue, but github's crude issue tracker seems to offer no way to do that (it's apparently possible to convert an issue to a PR, but oddly only via the API, not via the web UI).

A generic solution would be best as this doesn't just affect users of the packaged version in Debian (and derived distros).

I wondered about just checking if those fonts are present before outputting the lines to use them - in a known environment like Debian we know where TeX would install them so a suitable check could probably be a call to `stat()` or similar, but I'm not sure how easy that would be to achieve in a way which worked for any install of TeX (AIUI, there are several TeX distributions so I suspect the layout of the installed files may vary).  Running TeX on a simple test input is a more heavyweight test, but probably easier to achieve portably.  Thoughts?

**Comment by mbudaj** [comment]
> I wondered about just checking if those fonts are present before outputting the lines to use them

This seems to be a reasonable alternative.
- apt-get could test this by running a postinst script and then modify therion.ini accordingly
- in the windows installer all the fonts are always present (all take about 4 MB), so the fonts will be always declared

Or did you mean checking it in the run time?

**Comment by ojwb** [comment]
Checking in therion's postinst doesn't really work - it could only update the therion config to reflect what TeX fonts are installed **at the point in time when therion was last installed or upgraded**.  So if I install therion, then realise I want the extra fonts and install them, the therion config won't have them enabled (until the next therion upgrade, or unless I deliberately force a reinstall of the already installed version by hand).

Also, this issue is not specific to the Debian therion package (if I install therion from source on Debian, the same issue occurs), and unlikely to be specific to Debian and derived distros - any platform with a non-monolithic packaging of TeX is likely to split out fonts.  So a solution other packagers can easily reuse seems better.

I guess it's hard for therion to detect when it's going to need one of these fonts because the generated TeX probably needs the font setup at the start and you don't know all the characters being used without going over all the data, so that would probably require a dummy pass first, or else keeping track of characters in strings as they are read in.

Perhaps supporting something like this in `therion.ini`:

```
tex-fonts-optional raw cmr10 cmti10 cmbx10 cmss10 cmssi10
```

Platforms where you know the fonts are always present could stick to the current `therion.ini`.

**Comment by mbudaj** [comment]
> so that would probably require a dummy pass first, or else keeping track of characters

This would require too much effort to solve a marginal issue, I think.

**Comment by ojwb** [comment]
> This would require too much effort to solve a marginal issue, I think.

Indeed.

What do you think about something like `tex-fonts-optional`?

**Comment by smudrak** [comment]
I am sorry, what exactly would `tex-fonts-optional` do? Would it be processed by therion or by installer?

**Comment by ojwb** [comment]
> I am sorry, what exactly would tex-fonts-optional do?

Test if the specified font is available - if it is, it would act just like the existing `tex-fonts` command; if not, it would do nothing.

> Would it be processed by therion or by installer?

By therion - as I explained above, this can't be handle at therion install time, because the fonts may be installed (or uninstalled) after therion installed/updated.

**Comment by mbudaj** [comment]
Closing as tex-fonts-optional is implemented. Two related Debian patches should not be necessary any more.

**Comment by ojwb** [comment]
Awesome!

**Comment by wookey** [comment]
On 2017-02-22 11:30 -0800, Martin Budaj wrote:
> Closing as tex-fonts-optional is implemented. Two related Debian patches should
> not be necessary any more.

Excellent - this has been a (minor) issue since about 2004, so it's
nice to finally have a better solution.

Wookey
-- 
Principal hats:  Linaro, Debian, Wookware, ARM
http://wookware.org/

**Pull request closed without merging**
