### PR TITLE
New symbols EGB

### PR DESCRIPTION
**Pull request by rsevero**
Creation of several lines for the EGB symbol set.

### CODE REVIEW

**Comment by hbeni** [comment]
Hi Rodrigo,
are the new symbols accessible via xtherion already?

**Comment by rsevero** [comment]
Not all of them. And only in the version from git.

I expect tô finish it nexr week.

I don't kmow when there will be a new release.

Rodrigo

-------- Mensagem Original --------
Ativo 22 de dez de 2019 11:00, Benedikt Hallinger escreveu:

**Comment by hbeni** [comment]
Ah cool to hear you are on it already. Take your time!

**Comment by rsevero** [comment]
Will reaply these changes as per Martin request

**Pull request closed without merging**
