### PR TITLE
Use wx_str() with wxWidgets above 3.0.

### LINKED ISSUE #236: Error in wxChar* cast when compiling loch
I was compiling Therion on Opensuse with wxWidgets 3.0.4. Compilation of `loch/lxGUI.cxx` stops with the following error:

```
lxGUI.cxx:517:73: error: invalid cast from type ‘wxString’ to type ‘const wxChar*’ {aka ‘const wchar_t*’}
  517 | #define matchtype(w,t) if (fName.EndsWith((const wxChar *)wxString(_T(w)))) return t;
```

To fix it, I replaced line 517:
```
#define matchtype(w,t) if (fName.EndsWith((const wxChar *)wxString(_T(w)))) return t;
```
with:
```
#define matchtype(w,t) if (fName.EndsWith(wxString(_T(w)).GetData())) return t;
```

It seems to be OK according to wxWidgets documentation. Not sure if I should pull-request this fix, as it could break someone's else builds. Probably you should drop older versions of wxWidgets. Version 2.6 (which is minimal required according to Therion book) was released in 2005. It's _way_ too old.

### PR DESCRIPTION
**Pull request by sergeyext**
Fix #236.

### CODE REVIEW

**Comment by sergeyext** [comment]
My humble attempt to fix the build issue.

[Here](https://wiki.wxwidgets.org/Converting_everything_to_and_from_wxString) we can see that many things changed in major 3.0 release, so I added a macro that comapres wxWidgets version with 3.0.

Also, I used `wx_str()` instead of `GetData()`. Is it correct?

**Comment by smudrak** [comment]
Hi, I am sorry it took so much time to get to this issue.

So far we had no problem with wxWidgets 3.0. Could you pls specify, on which system (compiler, architecture) you are facing this issue with wxWidgets 3.0?

**Comment by speleo3** [comment]
Wouldn't `fName.EndsWith(wxT(w))` be more appropriate? Should be compatible with 2.x and 3.x.

**Comment by sergeyext** [comment]
> Hi, I am sorry it took so much time to get to this issue.
> 
> So far we had no problem with wxWidgets 3.0. Could you pls specify, on which system (compiler, architecture) you are facing this issue with wxWidgets 3.0?

Hello and sorry for being late too.

I tried to compile Therion from the latest commit on master (5d3fd7f2f902a0bafd1d1236d761d73f80a76bd5), the problem is still here.

Compiling on Linux (OpenSUSE) x64 with g++ 10.1.1, wxWidgets 3.0.4-3.5.
On previous attempt I used gcc 9, not remember the exact version number.

**Comment by smudrak** [comment]
Could you please check latest commit? It should fix the issue alternative way.

**Comment by sergeyext** [comment]
Yes, this particular issue is fixed, thanks!

**Pull request closed without merging**
