### PR TITLE
More options info for date and extra points

### PR DESCRIPTION
**Pull request by rsevero**
Some more info about the options available for date and extra points.

Please review the explanation of the -value option for the extra point I included. It's terrible but I don't really know what the -value option sets for the extra point.

### CODE REVIEW

**Comment by smudrak** [comment]
Hmmm, -value is the same, as -dist in the case of extra points. When extra morphing points were introduced, only -value option was available. Obviously, it was counterintuitive, therefore -dist synonym was introduced. If was not documented, that -value works, so I have removed support for it. I hope, it will not cause problems.

**Comment by CaverBruce** [comment]
I have rarely if ever used 'point extra', I must admit it was only a year or so ago that I really understood it.  Probably people that sketch in the cave using paper would use it though.
I think that as a general principle it would be better to keep both variants of synonym statements, to preserve as much backwards compatibility as possible.
It would be OK to indicate in the Therion Book that one option is preferred and the other deprecated, and for the therion.log to report that the deprecated variant is present and advise the user what statement to replace it with.  That at least allows a transition period.

**Comment by smudrak** [comment]
Hmmm, but until now, it was not in therion book, that -value is supported for extra points. But you are right, that removing backward compatibility is a bad idea in general. So I changed the error to a deprecation warning for this case. But I do not think, that adding deprecated features to thbook, if those are not there is necessary.

**Comment by CaverBruce** [comment]
OK, I agree.  I thought I learned of -value on the wiki, but maybe not.  It describes -dist.

**Pull request merged**
