### PR TITLE
Including Fedora pre-compile instructions in THBook

### PR DESCRIPTION
**Pull request by rsevero**
Including pre-compile isntructions for Fedora in Therion Book.

### CODE REVIEW

**Comment by Afforix** [comment]
```
sudo ln -s libnghttp2.so.14 /lib64/libnghttp2.so
```
Seems very specific, probably will work only on Fedora 37. I will try to test this in Docker.

**Comment by rsevero** [comment]
> ```
> sudo ln -s libnghttp2.so.14 /lib64/libnghttp2.so
> ```
> 
> Seems very specific, probably will work only on Fedora 37. I will try to test this in Docker.

You might be right. I believe it is a bug in nghttp2 package: it should create this link.

But this hack is necessary for Fedora 37 for sure.

**Comment by Afforix** [comment]
I think I have found solution to the symlink problem, `/lib64/libnghttp2.so` is a symlink to `/usr/lib64/libnghttp2.so`, which is installed by package `libnghttp2-devel`, so maybe you are just missing that package.

**Comment by rsevero** [comment]
> I think I have found solution to the symlink problem, `/lib64/libnghttp2.so` is a symlink to `/usr/lib64/libnghttp2.so`, which is installed by package `libnghttp2-devel`, so maybe you are just missing that package.

Yes! That's it. I don't know why/how I missing this particular devel package. Thanks!

**Comment by Afforix** [comment]
Nice! I also don't think that `export CMAKE_C_COMPILER=gcc` is necessary, CMake will find that without hints:
```
$ cmake ..
-- The C compiler identification is GNU 12.2.1
-- The CXX compiler identification is GNU 12.2.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
...

$ ll /usr/bin/cc
lrwxrwxrwx 1 root root 3 Nov 21 14:32 /usr/bin/cc -> gcc
```

**Comment by Afforix** [comment]
I don't need to set `CMAKE_C_COMPILER`  in my setup, so I would prefer not to mention it. And I also need package `texlive-collection-langczechslovak` to build `thbook`. Here is a Dockerfile which successfully builds therion:

```dockerfile
FROM fedora:37 as env

# install dependencies
RUN dnf upgrade -y && dnf install -y \
  brotli-devel \
  bwidget \
  cmake \
  g++ \
  jbigkit-devel \
  krb5-devel \
  libidn2-devel \
  libjpeg-turbo-devel \
  libnghttp2-devel \
  libpsl-devel \
  libssh-devel \
  libwebp-devel \
  openldap-devel \
  proj-devel \
  texlive-metapost \
  texlive-scheme-basic \
  tkimg \
  vtk-devel \
  wxGTK-devel

# does not work when installed together with other packages,
# probably issue with texlive setup
RUN dnf install -y texlive-collection-langczechslovak

FROM env as build

# download and compile therion
RUN dnf install -y git && git clone https://github.com/therion/therion.git
RUN cd therion && mkdir build && cd build && cmake .. && make -j 4
```

**Comment by rsevero** [comment]
> I don't need to set `CMAKE_C_COMPILER` in my setup, so I would prefer not to mention it. And I also need package `texlive-collection-langczechslovak` to build `thbook`. Here is a Dockerfile which successfully builds therion:
> 
> ```dockerfile
> FROM fedora:37 as env
> 
> # install dependencies
> RUN dnf upgrade -y && dnf install -y \
>   brotli-devel \
>   bwidget \
>   cmake \
>   g++ \
>   jbigkit-devel \
>   krb5-devel \
>   libidn2-devel \
>   libjpeg-turbo-devel \
>   libnghttp2-devel \
>   libpsl-devel \
>   libssh-devel \
>   libwebp-devel \
>   openldap-devel \
>   proj-devel \
>   texlive-metapost \
>   texlive-scheme-basic \
>   tkimg \
>   vtk-devel \
>   wxGTK-devel
> 
> # does not work when installed together with other packages,
> # probably issue with texlive setup
> RUN dnf install -y texlive-collection-langczechslovak
> 
> FROM env as build
> 
> # download and compile therion
> RUN dnf install -y git && git clone https://github.com/therion/therion.git
> RUN cd therion && mkdir build && cd build && cmake .. && make -j 4
> ```

Ok.

**Pull request merged**
