### PR TITLE
Elevation grid labeling updated to show both depth and altitude

### PR DESCRIPTION
**Pull request by vldgeorgiev**
The elevation grid shows the depth on one side and the elevation on the other. Each column has a header.
I find it more useful to see the depth of a cave in a 2D extended profile, rather than the elevation only.

### CODE REVIEW

**Comment by vldgeorgiev** [comment]
@smudrak @mbudaj 
Guys, did you have the time to review or comment on this one or #49 ?

**Comment by smudrak** [comment]
Hi, I am not sure about this... There is currently a discrepancy in therion.
If one wants to export "altitude" labels with "depth" numbers, all that needs to be done is to specify grid Z origin to desired entrance altitude. But when altitude grid is exported, it is ignored (I would consider it a bug). If this will be fixed, you can export depth labels without need of using "grid-coords" switch special way in elevation projections.

**Comment by vldgeorgiev** [comment]
Initially I tried setting the grid-origin, but it it is not compatible with the "cs" I use.
I set the coordinates/elevation with "cs lat-long" like "fix 1 12:13:14.5 11:12:13.4 1234", but then "grid-origin" requires all units to be meters, which is not compatible with the CS above. I don't know if this is a bug or a feature. If grid-origin is set to accept the same units as the CS, it will not be a problem.
I actually don't need the altitude much in extended profiles, so depth only will work wel.
Which bug do you mean exactly?

**Comment by smudrak** [comment]
The bug is, that grid-origin is ignored when drawing and labeling vertical grid in elevation.
It should be not. Not supporting cs lat-long in grid-origin is another bug, I will try to fix it.

**Comment by smudrak** [comment]
Well, I am not sure, but when I tried "cs lat-long" in layout and use DD:MM:SS as grid-origin coordinates,

    cs lat-long
    grid-origin 18:20:30 43:21:12 821.659932 m

it worked for me.

**Comment by vldgeorgiev** [comment]
Sorry, it was some time ago and I had forgotten. Adding the "cs" again with the grid-origin made it work, but didn't change the values printed. So this is the same bug you mentioned.
I will check how to fix it later.
The alignment also has to be changed if I recall. E.g. with "grid-origin 0" the 0 line will be at the topmost station.

**Comment by mbudaj** [comment]
Regarding grid-origin, for me it is a point where grid lines start, not where grid coordinates are set to zero, so I don't consider the current behaviour to be a bug. This makes it possible to draw grid lines e.g. at the coordinate values 5 - 15 - 25 instead of 0 - 10 - 20. 

Surely there is inconsistency in the current behaviour (as e.g. wall altitudes are affected by setting the grid-origin).

One way forward could be to introduce an additional parameter to set coordinates offset/origin in addition to grid (lines) origin.

**Pull request closed without merging**
